# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rmce_uploadr}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Vagin"]
  s.date = %q{2010-04-17}
  s.description = %q{Written in Ruby, using Sinatra}
  s.email = %q{alex@cloudware.it}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/rmce_uploadr.rb",
     "lib/rmce_uploadr/app/app.rb",
     "lib/rmce_uploadr/controllers.rb",
     "lib/rmce_uploadr/controllers/defaults.rb",
     "lib/rmce_uploadr/controllers/tiny_mce_plugin.rb",
     "lib/rmce_uploadr/public/images/rmce_uploadr_icon.png",
     "lib/rmce_uploadr/public/javascripts/rmce_uploadr.js",
     "lib/rmce_uploadr/public/javascripts/tiny_mce/plugins/rmce_uploadr/editor_plugin.js",
     "lib/rmce_uploadr/public/javascripts/tiny_mce/plugins/rmce_uploadr/editor_plugin_src.js",
     "lib/rmce_uploadr/views/index.erb",
     "lib/rmce_uploadr/views/layout.erb",
     "spec/models/image_spec.rb",
     "spec/rcov.opts",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/crhym3/rmce_uploadr}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Images uploader for TinyMCE}
  s.test_files = [
    "spec/models/image_spec.rb",
     "spec/spec_helper.rb",
     "examples/railsapp/app/controllers/application_controller.rb",
     "examples/railsapp/app/controllers/posts_controller.rb",
     "examples/railsapp/app/helpers/application_helper.rb",
     "examples/railsapp/app/helpers/posts_helper.rb",
     "examples/railsapp/app/metal/rmce_uploadr_metal.rb",
     "examples/railsapp/app/models/post.rb",
     "examples/railsapp/config/boot.rb",
     "examples/railsapp/config/environment.rb",
     "examples/railsapp/config/environments/development.rb",
     "examples/railsapp/config/environments/production.rb",
     "examples/railsapp/config/environments/test.rb",
     "examples/railsapp/config/initializers/backtrace_silencers.rb",
     "examples/railsapp/config/initializers/inflections.rb",
     "examples/railsapp/config/initializers/mime_types.rb",
     "examples/railsapp/config/initializers/new_rails_defaults.rb",
     "examples/railsapp/config/initializers/session_store.rb",
     "examples/railsapp/config/routes.rb",
     "examples/railsapp/db/migrate/20100417132216_create_posts.rb",
     "examples/railsapp/db/schema.rb",
     "examples/railsapp/db/seeds.rb",
     "examples/railsapp/test/functional/posts_controller_test.rb",
     "examples/railsapp/test/performance/browsing_test.rb",
     "examples/railsapp/test/test_helper.rb",
     "examples/railsapp/test/unit/helpers/posts_helper_test.rb",
     "examples/railsapp/test/unit/post_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 1.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<sinatra>, [">= 1.0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 1.0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

