source "http://gemcutter.org"

gem "rack", "= 1.0.1"
gem "rake", ">= 0.8.7"
gem "rack-flash", ">= 0.1.1"
gem "sinatra", ">= 1.0"
gem "activerecord", ">= 2.3.2"
gem "sqlite3-ruby", :require => "sqlite3"
gem "rmce_uploadr", "= 0.0.1"
